### ISSUE TITLE
publishing a message type on a topic using rmw_ecal_proto_cpp shows wrong type

### ISSUE THREAD

**Issue by karthiknit1** [eclipse-ecal/rmw_ecal#55]
Hi,

If there are two message types as below:

**std_msgs/msg/String.msg**
string data

**custom_msgs/msg/String.msg**
string data

First one is a standard message and second one is a custom message. Here if i run C++ talker node for message types "std_msgs::msg::String" and "custom_msgs::msg::String", I get the same type on rmw_ecal_proto_cpp. The type which I see on a ros2 Foxy terminal using "ros2 topic type /chatter" is "proto:String".

This seems to be incorrect. Ideally the type published over rmw layer should be "std_msgs/msg/String" and "custom_msgs/msg/String" in these two cases.

Could someone provide some insight on this issue and fix for this? I can see that in the file - https://github.com/eclipse-ecal/rmw_ecal/blob/master/rmw_ecal_proto_cpp/src/typesupport/proto_message_typesupport.hpp , "proto:" + GetMessageSimpleName() is being used as message type instead of GetMessageNamespace() + "/" +  GetMessageSimpleName(). I think this needs to be corrected, same applies to services as well.

Thanks
Karthik Reddy

**Comment by FlorianReimold** [comment]
Hey Karthik,

Do you have a setup where you can quickly try out that fix? PRs are always welcome, especially for the rmw_ecal / rosidl_typesupport_protobuf!

Kind Regards
Florian

**Comment by karthiknit1** [comment]
Hi Florian, 

I have opened a pull request for the same. Could you take action on this - https://github.com/eclipse-ecal/rmw_ecal/pull/57

Thanks,
Karthik Reddy

**Comment by FlorianReimold** [comment]
Fixed in #57
