### ISSUE TITLE
Current master branch is not compatible with Foxy or Galactic

### ISSUE THREAD

**Issue by JWhitleyWork** [eclipse-ecal/rmw_ecal#62]
Specifically the package `rmw_ecal_proto_cpp` is no longer compatible with Foxy or Galactic after 331dec6. I recommend creating a new branch just called `foxy` and another called `galactic` right after commit 0e6f2e3. This will allow the application of distribution-specific bugfixes and allow users to build a working version by just choosing the branch that matches their distro.

**Comment by FlorianReimold** [comment]
New branches created here:

Foxy: https://github.com/eclipse-ecal/rmw_ecal/tree/foxy
Galactic: https://github.com/eclipse-ecal/rmw_ecal/tree/galactic

the HEAD of both branches point to 0e6f2e395dc15e6a949ff2aea890e0f8190178c7

Please re-open if something went wrong!
